## Overiew Keras Core Layers
[Keras Core Layer Documentation](https://keras.io/layers/core/)

### Dense

A dense layer is a standard fully connected NN layer, let’s start with some sample source code:

```python
d = Dense(3, input_dim=3, kernel_initializer='uniform', activation='linear')
d.set_weights([np.array([[.1, .2, .5], [.1, .2, .5], [.1, .2, .5]]), np.array([0, 0, 0])])
print_out(d, [[10, 20, 30]])
# [[  6.  12.  30.]]
```

We see that the input [10,20,30] got converted to [6, 12, 30] using a linear activation layer and the weights [.1, .2, .5] for each input row.  
So taking the last output node which all weights are 0.5 we get the output (30) by calculating: 10\*0.5 + 20\*0.5 + 30\*0.5.  

### Activation

An activation function is a function that produces the layer output values by applying an arbitrary function to the input values of the layer.  
This function should have a useful derivative as this is used during the optimisation (backward) step of training.  
There are many standard activation functions used in NN a great visual summary of these common activation functions can be found at the bottom of the [Activation Function Wikipedia page](https://en.wikipedia.org/wiki/Activation_function). 

Partially reproduced here for convenience:

![Activation function (1)](../images/tbl1.png "Activation function")
![Activation function (2)](../images/tbl2.png "Activation function")
![Activation function (3)](../images/tbl3.png "Activation function")

The activation function specified in this layer is applied to each input element individually (element wise) so input data dimensions can be arbitrary.

```python
print_out(Activation('tanh'), [.5, 1, 2, 3])
# [ 0.46211714, 0.76159418, 0.96402758, 0.99505478 ]

print_out(Activation('softplus'), [.5, 1, 2, 3])
# [ 0.97407699, 1.31326163, 2.12692809, 3.04858732 ]

print_out(Activation('relu'), [-2, -1, 0, 1, 2])
# [ 0., 0., 0., 1., 2.]

print_out(Activation('sigmoid'), [.5, 1, 2, 3])
# [ 0.62245935, 0.7310586,  0.88079709, 0.95257413]

print_out(Activation('hard_sigmoid'), [.5, 1, 2, 3])
# [ 0.60000002, 0.69999999, 0.89999998, 1. ]

print_out(Activation('linear'), [.5, 1, 2, 3])
# [0.5, 1., 2., 3. ] – no weights set
```

### TimeDistributedDense

A very similar layer to the standard Dense layer with the exception that we are now working with an additional time dimension.  
So the input and output are in the shape: (nb_sample, time_dimension, input_dim).  
So reproducing the Dense example we get the following:

```python
d = TimeDistributedDense(3, init='uniform', activation='linear', input_dim=3)
d.set_weights([np.array([[.1, .2, .5], [.1, .2, .5], [.1, .2, .5]]), np.array([0, 0, 0])])
print_out(d, [[[10, 20, 30]]])
# [[[  6.  12.  30.]]]
# [0.5, 1., 2., 3. ] – no weights set
```

### Dropout

Dropout layers are used to reduce overfitting by randomly turning off inputs.  
It is important to note that Dropout only occurs during training.  During the test phase we do not turn off inputs.  
It is also very important to note that output values propagated forward (i.e. not turned off) must increase in value to compensate for the nodes being turned off.  
This means that the output value of the layer is the same with or without dropout.  
The following simple example shows this a little bit more intuitively:

```python
print_out(Dropout(.3), [1, 2, 3, 4, 5])
# [0, 0, 0, 5.71428585, 7.14285755]
```

So with 30% dropout we see that 3 output nodes were turned off (set to 0).  
To compensate for the output value of the layer all the other values were increased accordingly (probabilistically so they may not exactly match the output).

To tune dropout layers [Hinton suggests](http://www.cs.toronto.edu/~rsalakhu/papers/srivastava14a.pdf) training without dropout until a good layer settings are found.  
Then slowly increase dropout until optimal validation score is found after the layer.

### Reshape
The reshape layer reshapes input to a new shape.  
The number of dimensions however  must remain the same.

```python
print_out(Reshape((2, -1)), [[1, 2, 3, 4, 5, 6]])
# [[[ 1.  2.  3.], [ 4.  5.  6.]]]

print_out(Reshape((3, -1)), [[1, 2, 3, 4, 5, 6]])
# [[[ 1.  2.],[ 3.  4.],[ 5.  6.]]]
```

### Flatten
Flattens rows of a 3D matrix.

```python
print_out(Flatten(), [[[1, 2, 3], [4, 5, 6]]])
# [[ 1.  2.  3.  4.  5.  6.]]
```

### RepeatVector
Copies a 2D input matrix into a 3D matrix n times

```python
print_out(RepeatVector(RepeatVector), [[1, 2, 3]])
# [[[ 1.  2.  3.], [ 1.  2.  3.]]]
```

Source: http://www.picnet.com.au/blogs/guido/post/2016/05/16/review-of-keras-deep-learning-core-layers/